"""rename department

Revision ID: 006011445eb0
Revises: 82ada6a4a172
Create Date: 2024-04-11 20:57:28.341308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006011445eb0'
down_revision = '82ada6a4a172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
