"""rename address

Revision ID: 995fe7e241bb
Revises: 006011445eb0
Create Date: 2024-04-11 21:00:41.333193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995fe7e241bb'
down_revision = '006011445eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
